# Clock signal
set_property PACKAGE_PIN W5 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
# Switches
set_property PACKAGE_PIN V17 [get_ports {TX_IN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_IN[0]}]
set_property PACKAGE_PIN V16 [get_ports {TX_IN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_IN[1]}]
set_property PACKAGE_PIN W16 [get_ports {TX_IN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_IN[2]}]
set_property PACKAGE_PIN W17 [get_ports {TX_IN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_IN[3]}]
set_property PACKAGE_PIN W15 [get_ports {TX_IN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_IN[4]}]
set_property PACKAGE_PIN V15 [get_ports {TX_IN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_IN[5]}]
set_property PACKAGE_PIN W14 [get_ports {TX_IN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_IN[6]}]
set_property PACKAGE_PIN W13 [get_ports {TX_IN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_IN[7]}]
set_property PACKAGE_PIN U1 [get_ports {RESET}]
set_property IOSTANDARD LVCMOS33 [get_ports {RESET}]
set_property PACKAGE_PIN R2 [get_ports {AUTO}]
set_property IOSTANDARD LVCMOS33 [get_ports {AUTO}]
# LEDs
set_property PACKAGE_PIN U16 [get_ports {TXBUF_OUT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TXBUF_OUT[0]}]
set_property PACKAGE_PIN E19 [get_ports {TXBUF_OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TXBUF_OUT[1]}]
set_property PACKAGE_PIN U19 [get_ports {TXBUF_OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TXBUF_OUT[2]}]
set_property PACKAGE_PIN V19 [get_ports {TXBUF_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TXBUF_OUT[3]}]
set_property PACKAGE_PIN W18 [get_ports {TXBUF_OUT[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TXBUF_OUT[4]}]
set_property PACKAGE_PIN U15 [get_ports {TXBUF_OUT[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TXBUF_OUT[5]}]
set_property PACKAGE_PIN U14 [get_ports {TXBUF_OUT[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TXBUF_OUT[6]}]
set_property PACKAGE_PIN V14 [get_ports {TXBUF_OUT[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TXBUF_OUT[7]}]
set_property PACKAGE_PIN W3 [get_ports {pageout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pageout[0]}]
set_property PACKAGE_PIN U3 [get_ports {pageout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pageout[1]}]
set_property PACKAGE_PIN L1 [get_ports {posout}]
set_property IOSTANDARD LVCMOS33 [get_ports {posout}]
#7 segment display
set_property PACKAGE_PIN W7 [get_ports {SEGMENT_PATTERN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_PATTERN[6]}]
set_property PACKAGE_PIN W6 [get_ports {SEGMENT_PATTERN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_PATTERN[5]}]
set_property PACKAGE_PIN U8 [get_ports {SEGMENT_PATTERN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_PATTERN[4]}]
set_property PACKAGE_PIN V8 [get_ports {SEGMENT_PATTERN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_PATTERN[3]}]
set_property PACKAGE_PIN U5 [get_ports {SEGMENT_PATTERN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_PATTERN[2]}]
set_property PACKAGE_PIN V5 [get_ports {SEGMENT_PATTERN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_PATTERN[1]}]
set_property PACKAGE_PIN U7 [get_ports {SEGMENT_PATTERN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_PATTERN[0]}]
# no dp
set_property PACKAGE_PIN U2 [get_ports {ANODE[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ANODE[0]}]
set_property PACKAGE_PIN U4 [get_ports {ANODE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ANODE[1]}]
set_property PACKAGE_PIN V4 [get_ports {ANODE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ANODE[2]}]
set_property PACKAGE_PIN W4 [get_ports {ANODE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ANODE[3]}]
#Buttons
set_property PACKAGE_PIN U18 [get_ports TX_SEND_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports TX_SEND_DATA]
set_property PACKAGE_PIN T18 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property PACKAGE_PIN W19 [get_ports LEFT_PAGE]
set_property IOSTANDARD LVCMOS33 [get_ports LEFT_PAGE]
set_property PACKAGE_PIN T17 [get_ports RIGHT_PAGE]
set_property IOSTANDARD LVCMOS33 [get_ports RIGHT_PAGE]
set_property PACKAGE_PIN U17 [get_ports load]
set_property IOSTANDARD LVCMOS33 [get_ports load]
##Pmod Header JA
##Sch name = JA1
set_property PACKAGE_PIN J1 [get_ports {TX}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX}]
##Sch name = JA2
set_property PACKAGE_PIN L2 [get_ports {RX}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX}]